services:
  - type: web
    name: vtu-result-analysis
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: GMAIL_USER
        value: uttamabhise@gmail.com
      - key: GMAIL_APP_PASSWORD
        value: bkizjhjlvazlrxho
