services:
  - type: web
    name: vtu-result-scraper
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: GMAIL_USER
        value: uttamabhise@gmail.com
      - key: GMAIL_APP_PASSWORD
        value: bkizjhjlvazlrxho
      - key: WEB3FORMS_ACCESS_KEY
        value: 8708b761-cd16-4b79-ba2c-554eb547f017
      - key: DATA_DIR
        value: /app/backend/data
